// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_dashboard from "./routes/api/dashboard.ts";
import * as $api_ingest from "./routes/api/ingest.ts";
import * as $index from "./routes/index.tsx";
import * as $Chart from "./islands/Chart.tsx";
import * as $Dashboard from "./islands/Dashboard.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/dashboard.ts": $api_dashboard,
    "./routes/api/ingest.ts": $api_ingest,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Chart.tsx": $Chart,
    "./islands/Dashboard.tsx": $Dashboard,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
